CREATE TABLE IF NOT EXISTS User (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100),
    Username VARCHAR(100) UNIQUE,
    Email VARCHAR(100) UNIQUE,
    ProfileImage BLOB,
    Password VARCHAR(100),
    IsAdmin BOOLEAN,
    IsActive BOOLEAN,
    IsBlocked BOOLEAN
);
CREATE TABLE IF NOT EXISTS Friendship (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    FriendID INT,
    FOREIGN KEY (FriendID) REFERENCES User(UserID)
);