CREATE TABLE IF NOT EXISTS Client (
    ClientID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100),
    Email VARCHAR(100) UNIQUE,
    Password VARCHAR(100),
    IsAdmin BOOLEAN,
    IsActive BOOLEAN,
    IsBlocked BOOLEAN
);